#!/bin/bash
echo "AudioQuake Application Staging Area Script"
echo " - Places all files required for a build into a staging area"
echo "   (this includes the setup.py script)."
echo

. common.sh

# Variables...
D_BASE=`pwd`
chk_dir $D_MOD
D_ENG="zq-repo/zquake/release-mac"
LAUNCHER="AudioQuake.py"
ENG_SERVER="$D_ENG/zqds" ; chk_file $ENG_SERVER
ENG_CLIENT="$D_ENG/zquake-glsdl" ; chk_file $ENG_CLIENT

clean_ds

if [[ -d $D_APP ]]; then
	echo Removing existing .app...
	rm -rf $D_APP
fi

echo Making staging directory...
mkdir $D_APP

echo Copying in launcher...
cp -a $LAUNCHER $D_APP

echo Copying in engine...
cp $ENG_SERVER $ENG_CLIENT $D_APP/
cp $ENG_SERVER $ENG_CLIENT $D_APP/

echo Copying in mod...
cp -a $D_MOD $D_APP/$D_MOD/

echo Copying in shareware and mindgrid files...
cp -a quake-shareware-1.06/* $D_APP/
cp -a mindgrid-audio_quake_2003.09.22/* $D_APP/
rm $D_APP/pak2.pak  # it's already in id1/

echo Copying in README, legal and other .md files...
cp ../COPYING $D_APP/
cp ../*.md $D_APP/
cp *.md $D_APP/

echo Copying in setup script...
cp setup.py $D_APP/

echo build complete!
