#!/bin/bash
echo "AudioQuake Mod Compilation Script"
echo " - Ensures required data files are present;"
echo "   compiles QuakeC, creates up-to-date mod directory"
echo "   and puts it in the ZQuake installation"
echo

. common.sh

# Variables
D_BASE=`pwd`
D_ZQ_DEV_BASE="$D_BASE/zq-repo"
D_MOD="id1/"
D_MOD_DEV="agrip-dev/" ; chk_dir $D_MOD_DEV
D_QC="$D_ZQ_DEV_BASE/qc/agrip/" ; chk_dir $D_QC
D_ZQCCS="$D_ZQ_DEV_BASE/zqcc" ; chk_dir $D_ZQCCS
ZQCC="$D_ZQCCS/zqcc"
F_MAPS="https://dl.dropboxusercontent.com/sh/quqwcm244sqoh5a/8no8PzlJCW/devfiles/maps.zip"
F_DEMOS="https://dl.dropboxusercontent.com/sh/quqwcm244sqoh5a/HTM6QTjNTh/devfiles/demos.zip"
F_SKINS="https://dl.dropboxusercontent.com/sh/quqwcm244sqoh5a/QlAYOO3MLl/devfiles/skins.zip"
F_SHAREWARE="https://dl.dropboxusercontent.com/sh/quqwcm244sqoh5a/jhcvn0KyLd/data/quake-shareware-1.06.zip"
F_MINDGRID="https://dl.dropboxusercontent.com/sh/quqwcm244sqoh5a/tS5qRFx_Am/data/mindgrid-audio_quake_2003.09.22.zip"

# Check for commands
chk_cmd curl "downloading development resources"
chk_cmd unzip "uncompressing downloaded data"

if [[ -d $D_MOD ]]; then
    echo "Removing existing compiled $D_MOD tree..."
    rm -rf $D_MOD
fi

echo "Creating compiled mod ($D_MOD) directory..."
mkdir $D_MOD

echo "Checking for ZQCC..."
if [[ -x $ZQCC ]]; then
    $ZQCC > /dev/null
    if [[ $? == 126 ]]; then
        echo "ZQCC was compiled for another architecture; removing..."
        rm $ZQCC
    fi
fi
if [[ ! -x $ZQCC ]]; then
    echo "No ZQCC found; trying to make..."
    cd $D_ZQCCS
    make release > /dev/null 2> /dev/null
    cd - > /dev/null
fi
if [[ ! -x $ZQCC ]]; then
    echo "ZQCC Make failed -- perhaps you don't have a C++ compiler installed?"
    echo "Go to $D_ZQCCS to try to fix the problem."
    echo "Exiting..."
    exit 42
fi

echo "Compiling QC code..."
cd "$D_QC"
$ZQCC -progs progs.src > /dev/null
if [[ $? == "0" ]]; then
    echo "    qwprogs.dat OK"
else
    echo "    qwprogs.dat FAILED; running zqcc again, verbosely..."
    $ZQCC -progs progs.src
    exit 42
fi
$ZQCC -progs spprogs.src > /dev/null
if [[ $? == "0" ]]; then
    echo "    spprogs.dat OK"
else
    echo "    spprogs.dat FAILED; running zqcc again, verbosely..."
    $ZQCC -progs spprogs.src
    exit 42
fi
cd - > /dev/null

echo "Moving the .dat files to compiled mod directory ($D_MOD)..."
mv $D_QC/*.dat "$D_MOD"

echo "Copying dev mod directory's contents to compiled mod directory..."
cp -r $D_MOD_DEV/* "$D_MOD/"

# Get/copy in maps
get_summat \
	maps \
	maps/agdm01.bsp \
	maps \
	'Compile any maps you add and store them in the "maps" directory.' \
	$F_MAPS \
	'zip'
mkdir $D_MOD/maps
cp maps/*.bsp $D_MOD/maps/

# Get/copy in demos
get_summat \
	demos \
	demos/final2.dem \
	demos \
	'Compile any demos you add and store them in the "demos" directory.' \
	$F_DEMOS \
	'zip'
cp demos/* $D_MOD/

# Get/copy in skins
get_summat \
	skins \
	skins/base.pcx \
	skins \
	'Compile any skins you add and store them in the "skins" directory.' \
	$F_SKINS \
	'zip'
cp -r skins/ $D_MOD/

# Get/copy in shareware data
get_summat \
	quake-shareware-1.06 \
	quake-shareware-1.06/id1/pak0.pak \
	'shareware data' \
	'' \
	$F_SHAREWARE \
	'zip'
cp quake-shareware-1.06/id1/pak0.pak $D_MOD/

# Get/copy in shareware data
get_summat \
	mindgrid-audio_quake_2003.09.22 \
	mindgrid-audio_quake_2003.09.22/pak2.pak \
	'mindgrid sounds' \
	'' \
	$F_MINDGRID \
	'zip'
cp mindgrid-audio_quake_2003.09.22/pak2.pak $D_MOD/

echo Compilation complete!
