#!/bin/bash
./build && \
echo && echo ======================================================================= && echo && \
cd app-staging && \
cp -a /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/PyObjCTools . && \
cp -a /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py . && \
python setup.py bdist_mac
